name: email-sender-app
services:
  - name: web
    source_dir: /
    github:
      repo: Payhall123/email-sender-app
      branch: master
      deploy_on_push: true
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
